version: 2
jobs:
  build:
    working_directory: ~/blukutukhttp
    docker:
      - image: circleci/android:api-28-alpha
    machine:
      java:
        version: 'oraclejdk8'
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "blukutukhttp/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "blukutukhttp/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: blukutukhttp/build/reports
          destination: reports
      - store_test_results:
          path: blukutukhttp/build/test-results